import { Component, OnInit } from '@angular/core';
import { AccountService } from 'src/app/account.service';
import { AppComponent } from 'src/app/app.component';
import { CustomerfunctionalityComponent } from '../../customerfunctionality.component';
import { windowCount } from 'rxjs/operators';

@Component({
  selector: 'app-checquebookrequest',
  templateUrl: './checquebookrequest.component.html',
  styleUrls: ['./checquebookrequest.component.css']
})
export class ChecquebookrequestComponent implements OnInit {



  autoGeneratedChecqueBookId: any;
  constructor(public appcomponent: AppComponent, public customerfuncomp: CustomerfunctionalityComponent) {
    var flag = 0;
    for (var i = 0; i < appcomponent.accountDb.length; i++) {
      if (appcomponent.accountDb[i].userName == customerfuncomp.username){
      if (parseInt(appcomponent.accountDb[i].checqueBookId) == 0) {
          this.autoGeneratedChecqueBookId = (Math.floor(Math.random() * 1000) + 1);
          appcomponent.accountDb[i].checqueBookId = this.autoGeneratedChecqueBookId;
        }
        flag=1;
      } 
    }
    if(flag==0)
    {
      window.alert("Already Requested")
    }

  }



  ngOnInit(): void {
  }



}
