import { Component, OnInit } from '@angular/core';
import { AppComponent } from 'src/app/app.component';
import { CustomerfunctionalityComponent } from '../../customerfunctionality.component';

@Component({
  selector: 'app-creditcardrequest',
  templateUrl: './creditcardrequest.component.html',
  styleUrls: ['./creditcardrequest.component.css']
})
export class CreditcardrequestComponent implements OnInit {

  monthlyincome:any;
  autoGeneratedCreditCardId:any;
  submitted=false;

  constructor(public appcomponent:AppComponent,public customerfuncomp:CustomerfunctionalityComponent) 
  { 
  
  }

  ngOnInit(): void {
  }

  requestForCreditCard()
  {
   var flag=0;
    for(var i=0;i<this.appcomponent.accountDb.length;i++)
    {
      if(this.appcomponent.accountDb[i].userName==this.customerfuncomp.username)
      {
        if(this.appcomponent.accountDb[i].creditCardId==0)
        {
          this.autoGeneratedCreditCardId=(Math.floor(Math.random()*1000)+1);
        this.appcomponent.accountDb[i].creditCardId=this.autoGeneratedCreditCardId;
        this.appcomponent.accountDb[i].monthlyIncome=this.monthlyincome;
        console.log( this.appcomponent.accountDb[i].monthlyIncome);
        flag=1;
        }
        // else{
        //   this.autoGeneratedCreditCardId==this.appcomponent.accountDb[i].creditCardId;
        // }
      }
    }
    if(flag==0)
    {
      window.alert("Already Requested")
    }
    this.submitted=true;
  }

}
